// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QYV4us31_LWmyzB0jRzJgwUACp4XUm4',
    appId: '1:968460113065:web:286b160201a4328c5145b8',
    messagingSenderId: '968460113065',
    projectId: 'proyecto-i316kj',
    authDomain: 'proyecto-i316kj.firebaseapp.com',
    storageBucket: 'proyecto-i316kj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzBiE8ug-mp1FsGXNPnOqNwr_XcQSkwFo',
    appId: '1:968460113065:android:80e03daf1e5e06eb5145b8',
    messagingSenderId: '968460113065',
    projectId: 'proyecto-i316kj',
    storageBucket: 'proyecto-i316kj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBiMhhjG1zWkJ8R4q14AS6Flv19HaxPec',
    appId: '1:968460113065:ios:8a9b7f76c68ce4085145b8',
    messagingSenderId: '968460113065',
    projectId: 'proyecto-i316kj',
    storageBucket: 'proyecto-i316kj.firebasestorage.app',
    iosBundleId: 'com.example.tallerJwt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBiMhhjG1zWkJ8R4q14AS6Flv19HaxPec',
    appId: '1:968460113065:ios:8a9b7f76c68ce4085145b8',
    messagingSenderId: '968460113065',
    projectId: 'proyecto-i316kj',
    storageBucket: 'proyecto-i316kj.firebasestorage.app',
    iosBundleId: 'com.example.tallerJwt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6QYV4us31_LWmyzB0jRzJgwUACp4XUm4',
    appId: '1:968460113065:web:d55e560ae82829695145b8',
    messagingSenderId: '968460113065',
    projectId: 'proyecto-i316kj',
    authDomain: 'proyecto-i316kj.firebaseapp.com',
    storageBucket: 'proyecto-i316kj.firebasestorage.app',
  );
}
